version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit_mq
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
    volumes:
      - ./persistence/rabbitmq:/var/lib/rabbitmq

#  database_mongo:
#    image: mongo:6-jammy
#    container_name: database_mongo
#    hostname: mongodb
#    ports:
#      - '27017:27017'
#    env_file:
#      - .env
#    volumes:
#      - ./persistence/mongo-entrypoint:/docker-entrypoint-initdb.d
#      - ./persistence/mongodb:/data/db
#      - ./persistence/mongoconfig:/data/configdb
volumes:
#  mongodb:
#  mongoconfig:
  rabbitmq: