version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit_mq
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
    volumes:
      - ./persistence/rabbitmq:/var/lib/rabbitmq
volumes:
  rabbitmq:
